### ISSUE TITLE
Crash due to dbus name collision

### ISSUE THREAD

**Issue by CodeF53** [jpochyla/psst#564]
**Describe the bug**
```
$ RUST_BACKTRACE=1 psst-gui
...
[2024-12-06T03:42:28Z INFO  psst_core::session::access_token] access token expired, requesting
thread 'main' panicked at /home/cassie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:139:29:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
thread caused non-unwinding panic. aborting.
fish: Job 1, 'RUST_BACKTRACE=1 psst-gui' terminated by signal SIGABRT (Abort)
```

**Environment**
 - desktop enviroment: KDE Plasma (wayland)
 - kernel: 6.12.1-zen1-1-zen (64-bit)
 - Version: r547.0cd9904-1 (via [AUR](https://aur.archlinux.org/packages/psst-git)) 

**Additional context**

**Comment by jacksongoode** [comment]
Does this happen reliably? It seems to be triggered by zbus?

**Comment by CodeF53** [comment]
happened 100% reliably, I uninstalled and reinstalled and it fixed the issue

**Comment by SO9010** [comment]
The AUR is terribly out of date. Last update in 2022.

**Comment by jacksongoode** [comment]
Can we update that? I feel like the longer term solution is the #170 #141 #530 Flatpak support which was ALMOST finished 😂 but needs a little more of a nudge.

**Comment by SO9010** [comment]
I can probably update it! I also do want to look more into the flatpak support.

**Comment by SO9010** [comment]
Ill look into updating it now!

**Comment by ernstki** [comment]
Hi all,

I have 69314f9 built in November that exhibited this same problem. The circumstances were a loss of network connectivity when my laptop went into power save mode, with a track playing, and the crash was happening only after initial startup, upon trying to resume a playlist.

<details>
    <summary>Backtrace after running <code>RUST_BACKTRACE=full psst-gui</code></summary><pre><code>$ RUST_BACKTRACE=full psst-gui
[2024-12-21T09:18:38Z INFO  psst_gui::data::config] loading config: "/home/me/.config/Psst/config.json"
[2024-12-21T09:18:40Z INFO  psst_core::oauth] starting OAuth listener on 127.0.0.1:8888
[2024-12-21T09:18:40Z INFO  psst_core::oauth] listener bound successfully
[2024-12-21T09:18:49Z INFO  psst_core::connection] requesting AP list from http://apresolve.spotify.com
[2024-12-21T09:18:49Z INFO  psst_core::connection] received 6 APs from server
[2024-12-21T09:18:49Z INFO  psst_core::connection] successfully resolved 6 access points
[2024-12-21T09:18:49Z INFO  psst_core::connection] attempting to connect using 6 access points
[2024-12-21T09:18:49Z INFO  psst_core::connection] Trying AP 1 of 6: ap-guc3.spotify.com:4070
[2024-12-21T09:18:50Z INFO  psst_core::connection] successfully connected to AP: ap-guc3.spotify.com:4070
[2024-12-21T09:18:50Z ERROR psst_gui::webapi::client] failed to read local tracks: No such file or directory (os error 2)
[2024-12-21T09:18:50Z INFO  psst_gui::data::config] saved config: "/home/me/.config/Psst/config.json"
[2024-12-21T09:18:50Z INFO  psst_core::audio::output::cpal] using audio device: "default"
[2024-12-21T09:18:50Z INFO  psst_core::cache] using cache: "/home/me/.cache/Psst"
[2024-12-21T09:18:50Z INFO  psst_core::audio::output::cpal] opening output stream: StreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Default }
[2024-12-21T09:18:50Z INFO  psst_core::session::access_token] access token expired, requesting
[2024-12-21T09:18:50Z INFO  psst_core::connection] requesting AP list from http://apresolve.spotify.com
thread '&lt;unnamed&gt;' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:100:22:
called `Result::unwrap()` on an `Err` value: NameTaken
stack backtrace:
   0:     0x55b4be791b89 - &lt;unknown&gt;
   1:     0x55b4be34e19b - &lt;unknown&gt;
   2:     0x55b4be75be52 - &lt;unknown&gt;
   3:     0x55b4be792d88 - &lt;unknown&gt;
   4:     0x55b4be793c32 - &lt;unknown&gt;
   5:     0x55b4be793725 - &lt;unknown&gt;
   6:     0x55b4be793689 - &lt;unknown&gt;
   7:     0x55b4be793674 - &lt;unknown&gt;
   8:     0x55b4bdbb1062 - &lt;unknown&gt;
   9:     0x55b4bdbb1485 - &lt;unknown&gt;
  10:     0x55b4bdd313b9 - &lt;unknown&gt;
  11:     0x55b4bdd55a40 - &lt;unknown&gt;
  12:     0x55b4be79510b - &lt;unknown&gt;
  13:     0x7f43c6f09609 - start_thread
  14:     0x7f43c6cd7353 - clone
  15:                0x0 - &lt;unknown&gt;
[2024-12-21T09:18:50Z INFO  psst_core::connection] received 6 APs from server
[2024-12-21T09:18:50Z INFO  psst_core::connection] successfully resolved 6 access points
[2024-12-21T09:18:50Z INFO  psst_core::connection] attempting to connect using 6 access points
[2024-12-21T09:18:50Z INFO  psst_core::connection] Trying AP 1 of 6: ap-guc3.spotify.com:4070
[2024-12-21T09:18:50Z INFO  psst_core::connection] successfully connected to AP: ap-guc3.spotify.com:4070
[2024-12-21T09:19:13Z INFO  symphonia_format_ogg::demuxer] starting new physical stream
[2024-12-21T09:19:13Z INFO  symphonia_format_ogg::demuxer] selected vorbis mapper for stream with serial=0x0
[2024-12-21T09:19:13Z INFO  psst_core::player] starting playback
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:139:29:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
   0:     0x55b4be791b89 - &lt;unknown&gt;
   1:     0x55b4be34e19b - &lt;unknown&gt;
   2:     0x55b4be75be52 - &lt;unknown&gt;
   3:     0x55b4be792d88 - &lt;unknown&gt;
   4:     0x55b4be793c32 - &lt;unknown&gt;
   5:     0x55b4be793725 - &lt;unknown&gt;
   6:     0x55b4be793689 - &lt;unknown&gt;
   7:     0x55b4be793674 - &lt;unknown&gt;
   8:     0x55b4bdbb1062 - &lt;unknown&gt;
   9:     0x55b4bdbb1485 - &lt;unknown&gt;
  10:     0x55b4be70f073 - &lt;unknown&gt;
  11:     0x55b4bdc67491 - &lt;unknown&gt;
  12:     0x55b4bdef397e - &lt;unknown&gt;
  13:     0x55b4be0dff65 - &lt;unknown&gt;
  14:     0x55b4bdef397e - &lt;unknown&gt;
  15:     0x55b4bdef397e - &lt;unknown&gt;
  16:     0x55b4bdc758b0 - &lt;unknown&gt;
  17:     0x55b4be192f64 - &lt;unknown&gt;
  18:     0x55b4bdef397e - &lt;unknown&gt;
  19:     0x55b4be016759 - &lt;unknown&gt;
  20:     0x55b4bddfe827 - &lt;unknown&gt;
  21:     0x55b4bddf9c24 - &lt;unknown&gt;
  22:     0x55b4be1102b1 - &lt;unknown&gt;
  23:     0x55b4be38a509 - &lt;unknown&gt;
  24:     0x55b4be38a2ea - &lt;unknown&gt;
  25:     0x7f43c7b4e04e - g_main_context_dispatch
  26:     0x7f43c7b4e400 - &lt;unknown&gt;
  27:     0x7f43c7b4e4a3 - g_main_context_iteration
  28:     0x7f43c7021fe5 - g_application_run
  29:     0x55b4be2dde22 - &lt;unknown&gt;
  30:     0x55b4bdd33c33 - &lt;unknown&gt;
  31:     0x55b4be305534 - &lt;unknown&gt;
  32:     0x7f43c6bdc083 - __libc_start_main
  33:     0x55b4bdbd274e - &lt;unknown&gt;
  34:                0x0 - &lt;unknown&gt;
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x55b4be791b89 - &lt;unknown&gt;
   1:     0x55b4be34e19b - &lt;unknown&gt;
   2:     0x55b4be75be52 - &lt;unknown&gt;
   3:     0x55b4be792d88 - &lt;unknown&gt;
   4:     0x55b4be793c32 - &lt;unknown&gt;
   5:     0x55b4be7936f2 - &lt;unknown&gt;
   6:     0x55b4be793689 - &lt;unknown&gt;
   7:     0x55b4be793674 - &lt;unknown&gt;
   8:     0x55b4bdbb15b4 - &lt;unknown&gt;
   9:     0x55b4bdbb1615 - &lt;unknown&gt;
  10:     0x55b4bdbb15d0 - &lt;unknown&gt;
  11:     0x55b4be38a304 - &lt;unknown&gt;
  12:     0x7f43c7b4e04e - g_main_context_dispatch
  13:     0x7f43c7b4e400 - &lt;unknown&gt;
  14:     0x7f43c7b4e4a3 - g_main_context_iteration
  15:     0x7f43c7021fe5 - g_application_run
  16:     0x55b4be2dde22 - &lt;unknown&gt;
  17:     0x55b4bdd33c33 - &lt;unknown&gt;
  18:     0x55b4be305534 - &lt;unknown&gt;
  19:     0x7f43c6bdc083 - __libc_start_main
  20:     0x55b4bdbd274e - &lt;unknown&gt;
  21:                0x0 - &lt;unknown&gt;
thread caused non-unwinding panic. aborting.
Aborted</code></pre>
</details>

After some tinkering, it appears as if just logging out and back in through the app's settings solves this (for now).

I'm not inclined to _do_ anything about it at the moment, in terms of pulling a new version and rebuilding, because otherwise psst is working fine. However, if there's anything else I can do to help isolate which versions of which crates, or reporting a problem to some upstream crate, please let me know.

I do not know a thing about Rust myself, beyond `cargo build`, so be gentle.

**Comment by ernstki** [comment]
> The AUR is terribly out of date. Last update in 2022.

I don't know _that_ much about Arch and the AUR, but I don't think [the psst PKGBUILD script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=psst-git#n16) builds a specific version, just pulls from GitHub and [reports its version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=psst-git#n19) as whatever `HEAD` was at build time.

If `0cd9904` from the OP's report is the Git commit ID, then that's from September 2024, a mere 20 commits behind the version I built. Not sure AUR is strictly to blame here is all I'm saying.

**Comment by omartijn** [comment]
I'm now also running into this. Tried logging out and logging in again and the problem persisted. This is with latest `main` on a Debian Trixie system. x86_64 architecture.

**Comment by winteriscariot** [comment]
> Edit: Actually, just realized this happens when you open a _second_ instance of Psst. The second instance is non-functional.

Thanks for this, I ran into this issue cuz I had a zombie psst-gui process that had no gui element and was causing new instances to immediately crash when trying to play a song. killing that orphaned process fixed the issue.

**Comment by petermolnar** [comment]
And indeed, there was a zombie running, which caused my problem as well. Interesting.

**Comment by omartijn** [comment]
I just realized that the reason this happens to me sometimes is that I have omitted the `StartupWMClass=psst-gui` option in my local .desktop file. After adding this, I just get the existing window to the foreground when I try to open psst again.

**Comment by SO9010** [comment]
Does this fix the issue for others as well?

**Comment by ernstki** [comment]
> Does this fix the issue for others as well?

Running two instances and then attempting to _play_ in the second instance, while the first one is already playing, seems to cause this crash repeatably. Can the GUI app force itself to run only a single instance, to maybe avoid this?

I'm `git pull`ing the current version of the code to see if this still happens. I was running a slightly older build on the workstation I'm using at the moment.

**Comment by SO9010** [comment]
Thank you for this! 

Good idea of having a check to see if it's already running... 

We could have a simple bool in the config file which is loaded first in the program before the gui is run or anything else. 

@ernstki I'll add this hopefully tomorrow and maybe you could try it to see if it fixes it for you? If yes I'll reference the PR to you here!

**Comment by ernstki** [comment]
Sounds good, and yes I will test for you.

I also experienced a crash in the config parser in updating from whatever version I had checked out to the latest `main`. What is the project's policy on having the `config.json` be backwards-compatible?

If that sounds like a reportable bug, I'll try to `git bisect` for you to see where the bug first cropped up.

Here's a context diff of the changes required to avoid the crash. The backtrace, unfortunately, already rolled off the end of my terminal's scrollback buffer.

```diff
--- config.json.crashed	2025-05-05 16:40:27.660861223 -0400
+++ config.json	2025-05-05 16:40:34.584097626 -0400
@@ -7,29 +7,6 @@
   "audio_quality": "High",
   "theme": "Light",
   "volume": 1.0,
-  "last_route": {
-    "AlbumDetail": {
-      "id": "472IQn2kyszBiBt1fkwd2H",
-      "name": "Perplexagon",
-      "images": [
-        {
-          "url": "https://i.scdn.co/image/ab67616d0000b273de938199c03f8b7bc4536f72",
-          "width": 640,
-          "height": 640
-        },
-        {
-          "url": "https://i.scdn.co/image/ab67616d00001e02de938199c03f8b7bc4536f72",
-          "width": 300,
-          "height": 300
-        },
-        {
-          "url": "https://i.scdn.co/image/ab67616d00004851de938199c03f8b7bc4536f72",
-          "width": 64,
-          "height": 64
-        }
-      ]
-    }
-  },
   "queue_behavior": "Sequential",
   "show_track_cover": false,
   "window_size": {
```

**Comment by SO9010** [comment]
Ah yeah, it's not backwards compatible at all! Sorry about that... You can delete it that would fix it, or if you are comfortable with it go through and remove the variables that are causing the issue.

**Comment by ernstki** [comment]
> Ah yeah, it's not backwards compatible at all! Sorry about that... You can delete it that would fix it, or if you are comfortable with it go through and remove the variables that are causing the issue.

OK, I'll still file a bug and close it (linking to your comment), just so a workaround is documented.

I seriously doubt it will be, but if when I'm bisecting there seems like an obvious fix (obvious to not-a-real-Rust-programmer), I'll do a PR for it.

**Comment by SO9010** [comment]
We could add the optional field to the deserilizing of that json, but I question how many people use older versions of rust after updating? 

But if you want to have a go I'm happy to look through your PR and give some feedback!

**Comment by SO9010** [comment]
Update: Found the exact issue with dbus, just need to add a random uid for the dbus name so it doesn't overlap! 

Should be a pretty easy fix.

**Comment by ernstki** [comment]
> We could add the optional field to the deserilizing of that json, but I question how many people use older versions of rust after updating?

Insert "there is newer version than Java 8?" meme here. I admit, I always grumble a bit when a toolchain in the LTS Linux repositories is too old to build a project I'm interested in, but I get it. Rust is an evolving language!

Thanks to both of you for having a look at this!
